// ============================================================
// G26: Organization Model Types
// ============================================================
//
// Defines the data structures for hierarchical organization
// simulation: OrgUnit, WorkPackage, HandoffEvent, OrgRunResult.
//
// These are RESEARCH types — they do NOT replace the main
// gameplay pipeline (Order/Task/Agent/Workshop).
// ============================================================

import type { Domain, ArtifactKind, RiskLevel } from './types'
import type { OrgRole } from './orgRoles'

// ============================================================
// OrgUnit — a node in the organization hierarchy
// ============================================================

export interface OrgUnit {
  id: string
  name: string
  role: OrgRole
  /** Parent unit in hierarchy (null for top-level operations) */
  parentUnitId: string | null
  /** The lead agent assigned to this unit (null for worker pools) */
  leadAgentId: string | null
  /** Agents that belong to this unit */
  memberAgentIds: string[]
  /** Child org units */
  childUnitIds: string[]
  /** Domains this unit specializes in */
  specialization: Domain[]
  /** Max concurrent work packages this unit can handle */
  capacity: number
  /** Max direct child units this unit can effectively manage */
  spanOfControl: number
}

// ============================================================
// WorkPackage — a unit of work flowing through the org
// ============================================================

export type WorkPackageStage =
  | 'intake'
  | 'fanout'
  | 'execution'
  | 'merge'
  | 'validation'
  | 'audit'
  | 'delivery'

export type WorkPackageStatus = 'queued' | 'in_progress' | 'completed' | 'failed'

export interface WorkPackage {
  id: string
  orderId: string
  parentPackageId: string | null
  assignedUnitId: string
  leadAgentId: string | null
  workerAgentIds: string[]
  stage: WorkPackageStage
  status: WorkPackageStatus
  /** Child work packages created by fan-out */
  childPackageIds: string[]
  /** Artifacts generated by workers in this package */
  artifactIds: string[]
  /** Accumulated coordination cost from splits and merges */
  coordinationCost: number
  /** Number of handoff events for this package lifecycle */
  handoffCount: number
  /** Tick when created */
  createdAtTick: number
  /** Tick when status changed to completed/failed */
  completedAtTick: number | null
  /** Complexity inherited from order, scaled for this package */
  complexity: number
}

// ============================================================
// HandoffEvent — a transition of work between org units
// ============================================================

export type HandoffType = 'assign' | 'split' | 'merge' | 'escalate' | 'review'

export interface HandoffEvent {
  id: string
  tick: number
  fromUnitId: string
  toUnitId: string
  orderId: string
  packageId: string
  handoffType: HandoffType
  /** Human-readable summary of what happened */
  summary: string
  /** 0-10: how clear the handoff was (affects downstream quality) */
  clarityScore: number
  /** Tick cost added by this handoff */
  delayCost: number
}

// ============================================================
// OrgArtifact — a simplified artifact for org simulation
// ============================================================

export interface OrgArtifact {
  id: string
  orderId: string
  packageId: string
  createdByAgentId: string
  kind: ArtifactKind
  /** 0-10 quality score */
  quality: number
  /** 0-10 evidence support level */
  evidenceStrength: number
  /** 0-10 claim level (may exceed evidence) */
  claimLevel: number
  /** Number of defects found */
  defectCount: number
  /** Overclaim gap = claimLevel - evidenceStrength */
  overclaimGap: number
  /** Tick created */
  createdAtTick: number
}

// ============================================================
// OrgRunResult — complete output of an org scenario run
// ============================================================

export interface OrgRunMetrics {
  fanoutCount: number
  subtaskCount: number
  handoffCount: number
  coordinationCost: number
  mergeDelay: number
  leadUtilization: number
  workerUtilization: number
  bottleneckUnitId: string | null
  artifactDiversity: number
  parallelWaste: number

  finalQuality: number | null
  finalEvidenceStrength: number | null
  finalClaimLevel: number | null
  overclaimGap: number | null
  detectedOverclaimFindings: number
  latentRiskEstimate: number
  evidenceIntegrityDelta: number

  totalTicks: number
  artifactsProduced: number
}

export interface OrgRunResult {
  seed: number
  orderId: string
  orderTitle: string
  orderComplexity: number
  mode: 'flat' | 'hierarchical'

  finalArtifactId: string | null
  artifactIds: string[]
  workPackageIds: string[]
  handoffEvents: HandoffEvent[]

  metrics: OrgRunMetrics
}

// ============================================================
// Organization snapshot — full org state at a tick
// ============================================================

export interface OrgState {
  units: Record<string, OrgUnit>
  workPackages: Record<string, WorkPackage>
  artifacts: Record<string, OrgArtifact>
  handoffLedger: HandoffEvent[]
  tick: number
}
